import * as stylex from "@stylexjs/stylex";
import { colors, fontSize, radius, spacing } from "@/styles/tokens.stylex";

export const styles = stylex.create({
  root: {
    display: "flex",
    flex: 1,
    flexDirection: "column",
    overflow: "hidden",
    backgroundColor: colors.bgDark,
    borderRight: `1px solid ${colors.border}`,
    minWidth: 0,
    containerType: "inline-size",
    containerName: "chat",
  },
  messageList: {
    flex: 1,
    overflowY: "auto",
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    flex: 1,
    padding: spacing.xl,
    marginTop: "auto",
    marginBottom: "auto",
    minHeight: "200px",
  },
  emptyIcon: {
    color: colors.accent,
    fontSize: "48px",
    lineHeight: 1,
    opacity: 0.4,
  },
  emptyTitle: {
    color: colors.textMuted,
    fontSize: fontSize.lg,
    fontWeight: "600",
  },
  emptySubtitle: {
    color: colors.textSubtle,
    fontSize: fontSize.md,
    textAlign: "center",
    maxWidth: "320px",
    lineHeight: "1.6",
  },
  streamingRow: {
    display: "flex",
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
    paddingLeft: spacing.md,
    paddingRight: spacing.md,
  },
  streamingBubble: {
    backgroundColor: colors.bgSurface,
    border: `1px solid ${colors.accent}`,
    borderBottomLeftRadius: radius.sm,
    borderRadius: radius.lg,
    maxWidth: "90%",
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
    paddingLeft: spacing.md,
    paddingRight: spacing.md,
  },
  streamingLabel: {
    fontSize: fontSize.xs,
    color: colors.accent,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    marginBottom: spacing.xs,
  },
  streamingText: {
    color: colors.textMain,
    fontSize: fontSize.md,
    lineHeight: "1.6",
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  errorRow: {
    display: "flex",
    alignItems: "center",
    gap: spacing.sm,
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
    paddingLeft: spacing.md,
    paddingRight: spacing.md,
  },
  errorBubble: {
    backgroundColor: colors.bgSurface,
    border: `1px solid ${colors.danger}`,
    borderRadius: radius.lg,
    color: colors.danger,
    fontSize: fontSize.sm,
    flex: 1,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
    paddingLeft: spacing.md,
    paddingRight: spacing.md,
  },
  errorDismiss: {
    background: "none",
    border: "none",
    color: colors.textMuted,
    cursor: "pointer",
    fontSize: fontSize.sm,
    flexShrink: 0,
    padding: "4px",
    ":hover": { color: colors.textMain },
  },
  cursor: {
    width: "2px",
    height: "14px",
    backgroundColor: colors.accent,
    display: "inline-block",
    marginLeft: "2px",
    animationName: stylex.keyframes({
      "0%, 100%": { opacity: 1 },
      "50%": { opacity: 0 },
    }),
    animationDuration: "0.8s",
    animationIterationCount: "infinite",
    verticalAlign: "text-bottom",
  },
});
