import * as stylex from "@stylexjs/stylex";
import { colors, fontSize, radius, spacing } from "@/styles/tokens.stylex";

export const styles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    width: "340px",
    flexShrink: 0,
    backgroundColor: colors.bgSurface,
    overflow: "hidden",
  },
  rootCollapsed: {
    width: "36px",
    alignItems: "center",
    paddingTop: spacing.sm,
  },
  toggleBtn: {
    background: "none",
    border: "none",
    color: colors.textMuted,
    cursor: "pointer",
    fontSize: fontSize.lg,
    lineHeight: 1,
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
    paddingLeft: spacing.xs,
    paddingRight: spacing.xs,
    borderRadius: radius.sm,
    ":hover": {
      color: colors.textMain,
      backgroundColor: colors.bgElevated,
    },
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
    paddingLeft: spacing.md,
    paddingRight: spacing.sm,
    borderBottom: `1px solid ${colors.border}`,
    flexShrink: 0,
  },
  headerTitle: {
    fontSize: fontSize.xs,
    color: colors.textMuted,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: "0.06em",
  },
  collapseBtn: {
    background: "none",
    border: "none",
    color: colors.textMuted,
    cursor: "pointer",
    fontSize: fontSize.lg,
    lineHeight: 1,
    paddingTop: "2px",
    paddingBottom: "2px",
    paddingLeft: "4px",
    paddingRight: "4px",
    borderRadius: radius.sm,
    ":hover": {
      color: colors.textMain,
      backgroundColor: colors.bgElevated,
    },
  },
  tabs: {
    display: "flex",
    borderBottom: `1px solid ${colors.border}`,
    flexShrink: 0,
  },
  tab: {
    background: "none",
    border: "none",
    borderBottom: "2px solid transparent",
    color: colors.textMuted,
    cursor: "pointer",
    fontSize: fontSize.sm,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
    paddingLeft: spacing.md,
    paddingRight: spacing.md,
    transition: "color 0.15s, border-color 0.15s",
    ":hover": {
      color: colors.textMain,
    },
  },
  tabActive: {
    color: colors.accent,
    borderBottomColor: colors.accent,
  },
  body: {
    flex: 1,
    overflowY: "auto",
  },
  tabContent: {
    padding: spacing.md,
    display: "flex",
    flexDirection: "column",
    gap: spacing.md,
  },
  metricsGrid: {
    display: "flex",
    flexDirection: "column",
  },
  empty: {
    fontSize: fontSize.sm,
    color: colors.textSubtle,
    textAlign: "center",
    padding: spacing.lg,
  },
  emptyState: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: spacing.sm,
    padding: spacing.xl,
    minHeight: "200px",
    textAlign: "center",
  },
  emptyIcon: {
    fontSize: "32px",
    color: colors.textSubtle,
    opacity: 0.4,
  },
  emptyTitle: {
    fontSize: fontSize.md,
    color: colors.textMuted,
    fontWeight: "600",
  },
  emptySubtitle: {
    fontSize: fontSize.sm,
    color: colors.textSubtle,
    lineHeight: "1.6",
  },
  actionRow: {
    display: "flex",
    justifyContent: "flex-end",
  },
  sseEventList: {
    display: "flex",
    flexDirection: "column",
    gap: "1px",
    padding: spacing.sm,
  },
  sseEvent: {
    backgroundColor: colors.bgElevated,
    borderRadius: radius.sm,
    border: `1px solid ${colors.border}`,
    overflow: "hidden",
  },
  sseEventHeader: {
    display: "flex",
    alignItems: "center",
    paddingTop: "3px",
    paddingBottom: "3px",
    paddingLeft: spacing.sm,
    paddingRight: spacing.sm,
    borderBottom: `1px solid ${colors.border}`,
  },
  sseEventBadge: {
    fontSize: fontSize.xs,
    fontFamily: "monospace",
    color: colors.textMuted,
    backgroundColor: colors.bgDark,
    borderRadius: radius.sm,
    paddingTop: "1px",
    paddingBottom: "1px",
    paddingLeft: "5px",
    paddingRight: "5px",
  },
  sseEventBadgeDelta: {
    color: colors.success,
  },
  sseEventData: {
    fontSize: fontSize.xs,
    fontFamily: "monospace",
    color: colors.textSubtle,
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
    paddingLeft: spacing.sm,
    paddingRight: spacing.sm,
    margin: 0,
    overflowX: "auto",
    whiteSpace: "pre",
    lineHeight: "1.4",
  },
  curlBtn: {
    background: "none",
    border: `1px solid ${colors.border}`,
    borderRadius: radius.sm,
    color: colors.textMuted,
    cursor: "pointer",
    fontSize: fontSize.xs,
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
    paddingLeft: spacing.sm,
    paddingRight: spacing.sm,
    ":hover": {
      borderColor: colors.accent,
      color: colors.textMain,
    },
  },
});
