import * as stylex from "@stylexjs/stylex";
import { colors, fontSize, radius, spacing } from "@/styles/tokens.stylex";

export const styles = stylex.create({
  root: {
    display: "flex",
    flexDirection: "column",
    width: "240px",
    flexShrink: 0,
    backgroundColor: colors.bgSurface,
    borderRight: `1px solid ${colors.border}`,
    overflow: "hidden",
    containerType: "inline-size",
    containerName: "sidebar",
    flexWrap: "wrap",
    gap: "0.5rem",
    paddingInline: "0.1rem",
  },
  rootCollapsed: {
    width: "36px",
    alignItems: "center",
    paddingTop: spacing.sm,
  },
  toggleBtn: {
    background: "none",
    border: "none",
    color: colors.textMuted,
    cursor: "pointer",
    fontSize: fontSize.lg,
    lineHeight: 1,
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
    paddingLeft: spacing.xs,
    paddingRight: spacing.xs,
    borderRadius: radius.sm,
    ":hover": {
      color: colors.textMain,
      backgroundColor: colors.bgElevated,
    },
  },
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: spacing.xs,
  },
  collapseBtn: {
    background: "none",
    border: "none",
    color: colors.textMuted,
    cursor: "pointer",
    fontSize: fontSize.lg,
    lineHeight: 1,
    paddingTop: "2px",
    paddingBottom: "2px",
    paddingLeft: "4px",
    paddingRight: "4px",
    borderRadius: radius.sm,
    ":hover": {
      color: colors.textMain,
      backgroundColor: colors.bgElevated,
    },
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
    paddingLeft: spacing.md,
    paddingRight: spacing.sm,
    borderBottom: `1px solid ${colors.border}`,
    flexShrink: 0,
  },
  sectionTitle: {
    fontSize: fontSize.xs,
    color: colors.textMuted,
    textTransform: "uppercase",
    letterSpacing: "0.06em",
    fontWeight: "600",
  },
  newBtn: {
    backgroundColor: colors.accent,
    border: "none",
    borderRadius: radius.sm,
    color: colors.textMain,
    cursor: "pointer",
    fontSize: fontSize.xl,
    lineHeight: 1,
    paddingTop: "1px",
    paddingBottom: "1px",
    paddingLeft: "7px",
    paddingRight: "7px",
    ":hover": {
      backgroundColor: colors.accentHover,
    },
  },
  list: {
    flex: 1,
    overflowY: "auto",
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
    maxWidth: "100cqw",
    gap: "0.5rem",
    display: "flex",
    flexWrap: "wrap",
  },
  placeholder: {
    fontSize: fontSize.sm,
    color: colors.textSubtle,
    padding: spacing.md,
    textAlign: "center",
  },
  convItem: {
    height: "80px",
    width: "calc(100% - 8px)",
    backgroundColor: "none",
    border: "none",
    borderRadius: radius.sm,
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    gap: "2px",
    marginTop: "1px",
    marginBottom: "1px",
    marginLeft: "4px",
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
    paddingLeft: spacing.sm,
    paddingRight: spacing.sm,
    textAlign: "left",
    ":hover": {
      backgroundColor: colors.bgElevated,
    },
  },
  convItemActive: {
    backgroundColor: colors.bgElevated,
    outlineWidth: 0,
    borderLeft: `2px solid ${colors.accent}`,
  },
  convTop: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.xs,
  },
  convTitle: {
    fontSize: fontSize.md,
    color: colors.textMain,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    flex: 1,
  },
  deleteBtn: {
    background: "none",
    border: "none",
    color: colors.textSubtle,
    cursor: "pointer",
    fontSize: fontSize.lg,
    lineHeight: 1,
    padding: "2px",
    flexShrink: 0,
    opacity: 0.25,
    ":hover": {
      color: colors.danger,
      opacity: 1,
    },
  },
  convMeta: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: spacing.xs,
  },
  convVendor: {
    fontSize: fontSize.xs,
    color: colors.accent,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  },
  convDate: {
    fontSize: fontSize.xs,
    color: colors.textSubtle,
  },
});
