import * as stylex from "@stylexjs/stylex";
import { colors, fontSize, radius, spacing } from "@/styles/tokens.stylex";

export const styles = stylex.create({
  panel: {
    position: "relative",
    zIndex: 1,
    display: "flex",
    flexDirection: "column",
    width: "380px",
    height: "100%",
    backgroundColor: colors.bgSurface,
    borderLeft: `1px solid ${colors.border}`,
    overflowY: "auto",
  },
  header: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    paddingLeft: spacing.md,
    paddingRight: spacing.md,
    borderBottom: `1px solid ${colors.border}`,
    flexShrink: 0,
  },
  headerTitle: {
    fontSize: fontSize.md,
    color: colors.textMain,
    fontWeight: "600",
    letterSpacing: "-0.01em",
  },
  closeBtn: {
    background: "none",
    border: "none",
    color: colors.textMuted,
    cursor: "pointer",
    fontSize: fontSize.lg,
    lineHeight: 1,
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
    paddingLeft: spacing.xs,
    paddingRight: spacing.xs,
    borderRadius: radius.sm,
    textDecoration: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    ":hover": {
      color: colors.textMain,
      backgroundColor: colors.bgElevated,
    },
  },
  body: {
    display: "flex",
    flexDirection: "column",
    gap: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.lg,
    paddingLeft: spacing.md,
    paddingRight: spacing.md,
    flex: 1,
  },
  footer: {
    display: "flex",
    gap: spacing.sm,
    paddingTop: spacing.md,
    paddingBottom: spacing.md,
    paddingLeft: spacing.md,
    paddingRight: spacing.md,
    borderTop: `1px solid ${colors.border}`,
    flexShrink: 0,
  },
  section: {
    display: "flex",
    flexDirection: "column",
    gap: spacing.sm,
  },
  sectionLabel: {
    fontSize: fontSize.xs,
    color: colors.textSubtle,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    paddingBottom: "2px",
    borderBottom: `1px solid ${colors.border}`,
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
  },
  label: {
    fontSize: fontSize.xs,
    color: colors.textMuted,
    fontWeight: "500",
    letterSpacing: "0.03em",
  },
  select: {
    backgroundColor: colors.bgDark,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.sm,
    color: colors.textMain,
    fontSize: fontSize.md,
    paddingTop: "6px",
    paddingBottom: "6px",
    paddingLeft: spacing.sm,
    paddingRight: spacing.sm,
    outline: "none",
    cursor: "pointer",
    width: "100%",
    ":focus": {
      borderColor: colors.accent,
    },
  },
  input: {
    backgroundColor: colors.bgDark,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.sm,
    color: colors.textMain,
    fontSize: fontSize.md,
    paddingTop: "6px",
    paddingBottom: "6px",
    paddingLeft: spacing.sm,
    paddingRight: spacing.sm,
    outline: "none",
    width: "100%",
    ":focus": {
      borderColor: colors.accent,
    },
    "::placeholder": {
      color: colors.textSubtle,
    },
  },
  inputError: {
    borderColor: colors.danger,
    ":focus": {
      borderColor: colors.danger,
    },
  },
  fieldError: {
    fontSize: fontSize.xs,
    color: colors.danger,
    lineHeight: "1.3",
  },
  modelRow: {
    display: "flex",
    gap: spacing.xs,
  },
  modelSelect: {
    flex: 1,
    minWidth: 0,
  },
  fetchBtn: {
    backgroundColor: colors.bgElevated,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.sm,
    color: colors.textMain,
    cursor: "pointer",
    fontSize: fontSize.lg,
    paddingTop: "6px",
    paddingBottom: "6px",
    paddingLeft: spacing.sm,
    paddingRight: spacing.sm,
    flexShrink: 0,
    ":hover": {
      backgroundColor: colors.accent,
      borderColor: colors.accent,
    },
    ":disabled": {
      opacity: 0.5,
      cursor: "not-allowed",
    },
  },
  acceptBtn: {
    backgroundColor: colors.accent,
    border: `1px solid ${colors.accent}`,
    borderRadius: radius.sm,
    color: colors.textMain,
    cursor: "pointer",
    flex: 1,
    fontSize: fontSize.md,
    fontWeight: "600",
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
    paddingLeft: spacing.md,
    paddingRight: spacing.md,
    ":hover": {
      backgroundColor: colors.accentHover,
      borderColor: colors.accentHover,
    },
  },
  cancelBtn: {
    backgroundColor: "transparent",
    border: `1px solid ${colors.border}`,
    borderRadius: radius.sm,
    color: colors.textMuted,
    cursor: "pointer",
    flex: 1,
    fontSize: fontSize.md,
    paddingTop: spacing.sm,
    paddingBottom: spacing.sm,
    paddingLeft: spacing.md,
    paddingRight: spacing.md,
    ":hover": {
      borderColor: colors.textMuted,
      color: colors.textMain,
    },
  },
  modalOverlay: {
    position: "absolute",
    inset: 0,
    zIndex: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: `color-mix(in srgb, ${colors.bgDark} 70%, transparent)`,
  },
  modal: {
    backgroundColor: colors.bgElevated,
    border: `1px solid ${colors.border}`,
    borderRadius: radius.lg,
    display: "flex",
    flexDirection: "column",
    gap: spacing.md,
    marginLeft: spacing.md,
    marginRight: spacing.md,
    paddingTop: spacing.lg,
    paddingBottom: spacing.lg,
    paddingLeft: spacing.lg,
    paddingRight: spacing.lg,
    width: "100%",
  },
  modalTitle: {
    color: colors.textMain,
    fontSize: fontSize.lg,
    fontWeight: "600",
    margin: 0,
  },
  modalList: {
    display: "flex",
    flexDirection: "column",
    gap: spacing.xs,
    listStyle: "none",
    margin: 0,
    padding: 0,
  },
  modalListItem: {
    color: colors.danger,
    fontSize: fontSize.sm,
    paddingLeft: spacing.sm,
    position: "relative",
    "::before": {
      content: '"·"',
      left: 0,
      position: "absolute",
    },
  },
  modalBtn: {
    alignSelf: "flex-end",
    backgroundColor: colors.accent,
    border: `1px solid ${colors.accent}`,
    borderRadius: radius.sm,
    color: colors.textMain,
    cursor: "pointer",
    fontSize: fontSize.md,
    fontWeight: "600",
    paddingTop: spacing.xs,
    paddingBottom: spacing.xs,
    paddingLeft: spacing.md,
    paddingRight: spacing.md,
    ":hover": {
      backgroundColor: colors.accentHover,
      borderColor: colors.accentHover,
    },
  },
});
